spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proxydb
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

remote:
  proxy:
    source: https://freeapiproxies.azurewebsites.net/proxyapi
    validator: http://httpbin.org/ip