spring:
  cloud:
    function:
      definition: saveReport
    stream:
      bindings:
        saveReport-in-0:
          destination: report-sent
          group: ${spring.application.name}
        saveReport-out-0:
          destination: send-scenario
  datasource:
    url: jdbc:postgresql://localhost:5432/publisherdb
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state.enabled: true
    liveness-state.enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


server:
  port: 8082