spring:
  cloud:
    function:
      definition: saveReport
    stream:
      bindings:
        saveReport-in-0:
          destination: report-sent
          group: ${spring.application.name}
        saveReport-out-0:
          destination: send-scenario
#  datasource:
#    url: jdbc:h2:mem:testDb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ''
#  h2.console.enabled: true
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: create
#    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/publisherdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    jpa:
      hibernate.ddl-auto: update
      show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s